site_name: "lantoki"
site_url: "https://github.com/jetxeberria/lantoki"
site_dir: public
repo_name: "lantoki"
repo_url: "https://github.com/jetxeberria/lantoki"
site_description: "Internal documentation for lantoki"
site_author: "jetxeberria"
docs_dir: docs
copyright: MIT License

#strict: true

# Page tree
nav:
  - Home: index.md
  - Reference:
    - Python API: reference/index.md
  - Contributing: contributing.md
  - License: license.md

theme:
  name: material
  custom_dir: docs/theme
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra:
  url_prefix: !ENV MM_DOCS_URL_PREFIX
  generator: false
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/9.0.1/mermaid.min.js
plugins:
  - awesome-pages
  - search
  - mermaid2:
      arguments:
        theme: |
          ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
  - site-urls
  - mkdocstrings:
      # Options awesome from fastapi docs
      # Full reference: https://mkdocstrings.github.io/python/usage/configuration/general
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            extensions:
            - griffe_typingdoc
            show_source: false
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - build_plantuml:
      render: 'server'
      server: 'http://www.plantuml.com/plantuml'
      output_format: 'png'
      diagram_root: 'docs/diagrams'
      output_folder: 'build'
      input_folder: 'src'
  - render_swagger
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: .
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - pymdownx.critic
  - footnotes
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - meta
use_directory_urls: false
